---
- name: Install tomcat
  hosts: test
  become: yes
  tasks:
    - name: Install and configure JAVA
      yum:
        name: 
          - java-1.8.0-openjdk-devel
        state: installed

    - name: Check java Installation and version
      command: "java -version"
      register: version

    - name: Display version
      debug:
        var: version.stderr_lines

    - name: download tomcat packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /root/tomcat9.tar.gz

    - name: Unarchive apache tomcat
      unarchive:
        src: /root/tomcat9.tar.gz
        dest: /opt/
        remote_src: yes

    - name: change permissions
      file: 
        path: /opt/apache-tomcat-9.0.65/bin/startup.sh
        mode: 777
      become: yes
        
    - name: start tomcat
      command: /opt/apache-tomcat-9.0.65/bin/startup.sh
