---
- hosts: dev
  become: true
  tasks:
    - name: Install neccessary packages
      yum:
        name:
          - java-1.8.0-openjdk-devel
          - tar
          - wget
        state: installed
    - name: Check java Installation and version
      command: "java -version"
      register: version
    - name: Display version
      debug:
        var: version.stderr_lines
    - name: Download tomcat packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /usr/local/
    - name: extract tar archive
      unarchive:
        src: /usr/local/apache-tomcat-9.0.65.tar.gz
        dest: /usr/local/
        remote_src: true
    - name: rename to tomcat 9
      command: "mv /usr/local/apache-tomcat-9.0.65 /usr/local/tomcat9"
      ignore_errors: true
    - name: create tomcat user
      user:
        name: tomcat
        state: present
    - name: Change permissions
      file:
        path: /usr/local/tomcat9
        owner: tomcat
        group: tomcat
        recurse: true
    - name: Create tomcat service file
      template:
        src: files/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
    - name: reload systemd
      systemd:
        daemon-reload: true
    - name: Add firewall 8080 rule
      firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
        immediate: yes
    - name: start tomcat service
      service:
        name: tomcat
        state: started
        enabled: true

