---
- name: War File Deploy tomcat tomcat
  hosts: test
  become: yes
  tasks:
    - name: Test url
      uri:
        url: http://servere.example.com:8080
        status_code: 200
        return_content: yes
    - name: Stop tomcat server
      service:
        name:
        state: stopped
    - name: delete existing war file
      file:
        path: /opt/tomcat/tomcat/webapps/hello.war
        state: absent
    - name: download new deployment file
      git:
        url: https://github.com/tomhac3k/tomcat
        dest: /opt/tomcat/tomcat/webapps/hello.war
    - name: set file permissions
      file: 
        path: /opt/tomcat/tomcat/webapps/hello.war
        mode: 0644
        user: tomcat
        group: tomcat
      notify: start tomcat
    - name: check URL status
      uri:
        url: ansible.example.com:8080/hello/hi
        return_content: yes
        status_code: 200
  handlers:
    - name: start tomcat
      service:
        name: tomcat
        state: started
