name: My first Woekflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome Message
      run:  echo "My first Workflow and GitHub Actions"
    
    - name: List Files
      run: ls

    - name: Read File
      run: cat README.md